
import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '@/contexts/AuthContext.jsx';
import api from '@/lib/api.js';
import { Card, CardContent, CardHeader, CardTitle, CardFooter } from '@/components/ui/card.jsx';
import { Input } from '@/components/ui/input.jsx';
import { Button } from '@/components/ui/button.jsx';
import { Label } from '@/components/ui/label.jsx';
import { Textarea } from '@/components/ui/textarea.jsx';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select.jsx';
import { toast } from 'sonner';
import { Loader2, UploadCloud, File as FileIcon, X, Star } from 'lucide-react';
import SectionHeader from '@/components/common/SectionHeader.jsx';

export default function CreateTicketPage() {
  const { currentUser } = useAuth();
  const navigate = useNavigate();
  const [isLoading, setIsLoading] = useState(false);
  const [isCheckingRating, setIsCheckingRating] = useState(true);
  const [pendingRatingTicket, setPendingRatingTicket] = useState(null);
  const [files, setFiles] = useState([]);
  
  const [formData, setFormData] = useState({
    title: '',
    description: '',
    location: '',
    category: 'Umum'
  });

  // Cek apakah ada permohonan Selesai yang belum dirating

  useEffect(() => {
    api.get('/tickets/pending-rating')
      .then(({ data }) => {
        if (data.pending && data.ticket) {
          setPendingRatingTicket(data.ticket);
        }
      })
      .catch(() => {/* tidak kritis */})
      .finally(() => setIsCheckingRating(false));
  }, []);

  const handleChange = (e) => setFormData(prev => ({ ...prev, [e.target.id]: e.target.value }));

  const handleFileChange = (e) => {
    if (e.target.files) {
      const newFiles = Array.from(e.target.files);
      if (files.length + newFiles.length > 5) {
        toast.error('Maksimal 5 lampiran diperbolehkan');
        return;
      }
      setFiles(prev => [...prev, ...newFiles]);
    }
  };

  const removeFile = (index) => {
    setFiles(prev => prev.filter((_, i) => i !== index));
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    
    if (!formData.title || !formData.description || !formData.location) {
      toast.error('Mohon lengkapi semua field yang wajib');
      return;
    }

    if (!formData.category) {
      toast.error('Mohon pilih kategori permohonan');
      return;
    }

    setIsLoading(true);
    try {
      // Ticket number will be generated by backend
      const ticketData = {
        title: formData.title,
        description: formData.description,
        location: formData.location,
        category: formData.category
      };

      const { data: ticketRecord } = await api.post('/tickets', ticketData);

      // Extract ticket from ApiResponse wrapper safely
      const ticket = ticketRecord?.data?.ticket || ticketRecord?.ticket || ticketRecord;
      if (!ticket?.id) {
        throw new Error('Respons permohonan tidak valid dari server');
      }
      const ticketNumber = ticket.ticket_number || ticket.id;

      // Upload attachments (multipart/form-data) to the uploads endpoint.
      if (files.length > 0) {
        const formData = new FormData();
        files.forEach((file) => {
          formData.append('files', file);
        });

        await api.post(`/uploads/ticket/${ticket.id}`, formData, {
          headers: {
            'Content-Type': 'multipart/form-data'
          }
        });
      }

      toast.success(`Permohonan ${ticketNumber} berhasil dibuat`);
      navigate('/satker/tickets');
    } catch (error) {
      const data = error.response?.data;
      // Jika server menolak karena ada rating pending, redirect ke halaman rating
      if (data?.pendingRating) {
        toast.warning('Harap beri rating permohonan sebelumnya terlebih dahulu.');
        navigate(`/satker/rating?ticket_id=${data.ticket_id}`);
        return;
      }
      const detail = Array.isArray(data?.errors) && data.errors.length
        ? data.errors.map(e => e.message).join(', ')
        : (data?.message || error.message);
      toast.error('Gagal membuat permohonan: ' + detail);
    } finally {
      setIsLoading(false);
    }
  };

  // Jika ada pending rating, tampilkan banner dan blokir akses form
  if (!isCheckingRating && pendingRatingTicket) {
    return (
      <div className="w-full space-y-6 animate-in fade-in duration-500">
        <SectionHeader title="Buat Permohonan Baru" subtitle="Laporkan masalah IT Anda" />
        <Card className="border-amber-400 bg-amber-50 dark:bg-amber-950/20 dark:border-amber-700 shadow-sm">
          <CardContent className="p-6 space-y-4">
            <div className="flex items-start gap-3">
              <Star className="h-6 w-6 text-amber-500 mt-0.5 flex-shrink-0" />
              <div className="space-y-1">
                <p className="font-semibold text-amber-800 dark:text-amber-300">Rating Diperlukan</p>
                <p className="text-sm text-amber-700 dark:text-amber-400">
                  Anda perlu memberi rating pada permohonan{' '}
                  <span className="font-mono font-semibold">{pendingRatingTicket.ticket_number}</span>{' '}
                  sebelum dapat membuat permohonan baru.
                </p>
              </div>
            </div>
            <Button
              onClick={() => navigate(`/satker/rating?ticket_id=${pendingRatingTicket.id}`)}
              className="bg-amber-500 hover:bg-amber-600 text-white w-full sm:w-auto"
            >
              <Star className="mr-2 h-4 w-4" />
              Beri Rating Sekarang
            </Button>
          </CardContent>
        </Card>
      </div>
    );
  }

  return (
    <div className="w-full space-y-6 animate-in fade-in duration-500">
      <SectionHeader
        title="Buat Permohonan Baru"
        subtitle="Laporkan masalah IT Anda"
      />

      <Card className="border-border shadow-sm">
        <form onSubmit={handleSubmit}>
          <CardHeader>
            <CardTitle className="text-base">Detail Laporan</CardTitle>
          </CardHeader>
          <CardContent className="p-6 space-y-6">
            
            <div className="grid sm:grid-cols-2 md:grid-cols-2 gap-4 p-4 bg-muted/40 rounded-xl border border-border">
              <div className="space-y-1">
                <Label className="text-xs text-muted-foreground uppercase tracking-wider">Pelapor</Label>
                <div className="font-medium text-sm">{currentUser?.name}</div>
              </div>
              <div className="space-y-1">
                <Label className="text-xs text-muted-foreground uppercase tracking-wider">No. Telepon</Label>
                <div className="font-medium text-sm">{currentUser?.phone || '-'}</div>
              </div>
            </div>

            <div className="space-y-4">
              <div className="space-y-2">
                <Label htmlFor="title">Judul Kendala <span className="text-destructive">*</span></Label>
                <Input 
                  id="title" 
                  placeholder="Contoh: Jaringan WiFi di lantai 2 terputus" 
                  value={formData.title}
                  onChange={handleChange}
                  className="text-foreground"
                  disabled={isLoading}
                />
              </div>

              <div className="space-y-2">
                <Label htmlFor="description">Deskripsi Detail <span className="text-destructive">*</span></Label>
                <Textarea 
                  id="description" 
                  placeholder="Jelaskan secara detail kendala yang dialami..." 
                  className="min-h-[120px] resize-y text-foreground"
                  value={formData.description}
                  onChange={handleChange}
                  disabled={isLoading}
                />
              </div>

              <div className="space-y-2">
                <Label htmlFor="location">Lokasi <span className="text-destructive">*</span></Label>
                <Input 
                  id="location" 
                  placeholder="Contoh: Ruang Meeting A" 
                  value={formData.location}
                  onChange={handleChange}
                  className="text-foreground"
                  disabled={isLoading}
                />
              </div>

              <div className="space-y-2">
                <Label htmlFor="category">Kategori <span className="text-destructive">*</span></Label>
                <Select
                  value={formData.category}
                  onValueChange={(value) => setFormData(prev => ({ ...prev, category: value }))}
                  disabled={isLoading}
                >
                  <SelectTrigger id="category">
                    <SelectValue placeholder="Pilih Kategori" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="Jaringan">Jaringan</SelectItem>
                    <SelectItem value="Hardware">Hardware</SelectItem>
                    <SelectItem value="Software">Software</SelectItem>
                    <SelectItem value="Akses Sistem">Akses Sistem</SelectItem>
                    <SelectItem value="Umum">Umum</SelectItem>
                    <SelectItem value="Lainnya">Lainnya</SelectItem>
                  </SelectContent>
                </Select>
              </div>

              <div className="space-y-2 pt-2">
                <Label>Lampiran (Opsional)</Label>
                <div className="border-2 border-dashed border-border rounded-xl p-6 text-center hover:bg-muted/50 transition-colors">
                  <Input 
                    type="file" 
                    id="files" 
                    multiple 
                    className="hidden" 
                    onChange={handleFileChange}
                    disabled={isLoading || files.length >= 5}
                  />
                  <Label htmlFor="files" className="cursor-pointer flex flex-col items-center gap-2 focus-visible:ring-2 focus-visible:ring-primary" tabIndex={0} aria-label="Unggah file lampiran">
                    <div className="p-3 bg-primary/10 text-primary rounded-full">
                      <UploadCloud className="h-6 w-6" />
                    </div>
                    <span className="font-medium text-sm text-foreground">Klik untuk unggah file</span>
                    <span className="text-xs text-muted-foreground">Maksimal 5 file (Gambar, Dokumen)</span>
                  </Label>
                </div>

                {files.length > 0 && (
                  <div className="mt-4 space-y-2">
                    {files.map((f, i) => (
                      <div key={i} className="flex items-center justify-between p-3 bg-muted rounded-lg border border-border">
                        <div className="flex items-center gap-3 overflow-hidden">
                          <FileIcon className="h-5 w-5 text-muted-foreground flex-shrink-0" />
                          <span className="text-sm font-medium truncate">{f.name}</span>
                          <span className="text-xs text-muted-foreground flex-shrink-0">
                            {(f.size / 1024 / 1024).toFixed(2)} MB
                          </span>
                        </div>
                        <Button 
                          type="button" 
                          variant="ghost" 
                          size="icon" 
                          onClick={() => removeFile(i)}
                          disabled={isLoading}
                          className="text-muted-foreground hover:text-destructive flex-shrink-0"
                        >
                          <X className="h-4 w-4" />
                        </Button>
                      </div>
                    ))}
                  </div>
                )}
              </div>
            </div>

          </CardContent>
          <CardFooter className="border-t pt-6 flex justify-end gap-3">
            <Button type="button" variant="outline" onClick={() => navigate(-1)} disabled={isLoading}>
              Batal
            </Button>
            <Button type="submit" disabled={isLoading}>
              {isLoading ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : null}
              {isLoading ? 'Menyimpan...' : 'Kirim Permohonan'}
            </Button>
          </CardFooter>
        </form>
      </Card>
    </div>
  );
}
